services:
  certbot_init:
    env_file:
      - ../../components/librebooking/nginx/librebooking.env
  nginx:
    env_file:
      - ../../components/librebooking/nginx/librebooking.env
    volumes:
      - ../../components/librebooking/nginx/templates/librebooking.conf.template:/etc/nginx/templates/librebooking.conf.template
